### PR TITLE
Handles "latest" special value for scanner_version

### PR DESCRIPTION
**Pull request by DayS**
Instead of updating the default version for every release of the Scanner, this PR handle a `latest` value for the `scanner_version` input.

In this case, the script will use the Github API to fetch the last public release of Sonnar-scanner from the [official repository](https://github.com/SonarSource/sonar-scanner-cli).

The use can still use a specific version if needed.

### CODE REVIEW

**Comment by koral--** [comment]
Adding the support for `latest` version is perfectly fine.
However, changing the default value to latest shouldn't be done.
Workflows which have it unset will become not reproducible after updating the step version.

**Comment by DayS** [comment]
It makes sense, I'll update PR to rollback to the fixed version `4.3.0.2102` as default.

**Review by koral-- — APPROVED** [review]

**Comment by koral--** [comment]
Thanks, I'll fix CI ASAP.

**Comment by DayS** [comment]
Perfect. I'm looking forward the new version on Bitrise :)

**Pull request merged**
